// <auto-generated />
using System;
using MagicVilla_VillaAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MagicVilla_VillaAPI.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20250310104511_SeedVillaTableWithCreatedDateAndUTC")]
    partial class SeedVillaTableWithCreatedDateAndUTC
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MagicVilla_VillaAPI.Models.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Amenity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Occupancy")
                        .HasColumnType("int");

                    b.Property<double>("Rate")
                        .HasColumnType("float");

                    b.Property<int>("Sqft")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Villas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amenity = "",
                            CreatedDate = new DateTime(2025, 3, 10, 10, 45, 11, 226, DateTimeKind.Utc).AddTicks(7933),
                            Details = "Lorem whateevr this that",
                            ImageUrl = "",
                            Name = "Royal Villa",
                            Occupancy = 5,
                            Rate = 200.0,
                            Sqft = 550,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Amenity = "Pool, Garden, Spa",
                            CreatedDate = new DateTime(2025, 3, 10, 10, 45, 11, 226, DateTimeKind.Utc).AddTicks(8134),
                            Details = "Lorem whatever this that.",
                            ImageUrl = "https://example.com/royal_villa.jpg",
                            Name = "Royal Villa",
                            Occupancy = 5,
                            Rate = 200.0,
                            Sqft = 550,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Amenity = "Sauna, Fireplace, Hiking Trails",
                            CreatedDate = new DateTime(2025, 3, 10, 10, 45, 11, 226, DateTimeKind.Utc).AddTicks(8136),
                            Details = "A peaceful retreat in the mountains.",
                            ImageUrl = "https://example.com/mountain_retreat.jpg",
                            Name = "Mountain Retreat",
                            Occupancy = 4,
                            Rate = 250.0,
                            Sqft = 450,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            Amenity = "Beach Access, Hot Tub",
                            CreatedDate = new DateTime(2025, 3, 10, 10, 45, 11, 226, DateTimeKind.Utc).AddTicks(8137),
                            Details = "Enjoy breathtaking ocean views.",
                            ImageUrl = "https://example.com/seaside_escape.jpg",
                            Name = "Seaside Escape",
                            Occupancy = 6,
                            Rate = 300.0,
                            Sqft = 600,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            Amenity = "Gym, Rooftop Terrace, Bar",
                            CreatedDate = new DateTime(2025, 3, 10, 10, 45, 11, 226, DateTimeKind.Utc).AddTicks(8138),
                            Details = "A luxurious villa in the heart of the city.",
                            ImageUrl = "https://example.com/city_oasis.jpg",
                            Name = "City Oasis",
                            Occupancy = 3,
                            Rate = 180.0,
                            Sqft = 400,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            Amenity = "Pool, Desert Safari, Star Gazing",
                            CreatedDate = new DateTime(2025, 3, 10, 10, 45, 11, 226, DateTimeKind.Utc).AddTicks(8139),
                            Details = "An exotic villa amidst the desert.",
                            ImageUrl = "https://example.com/desert_mirage.jpg",
                            Name = "Desert Mirage",
                            Occupancy = 4,
                            Rate = 220.0,
                            Sqft = 500,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            Amenity = "Forest Trails, Yoga Studio",
                            CreatedDate = new DateTime(2025, 3, 10, 10, 45, 11, 226, DateTimeKind.Utc).AddTicks(8141),
                            Details = "A serene escape surrounded by nature.",
                            ImageUrl = "https://example.com/forest_haven.jpg",
                            Name = "Forest Haven",
                            Occupancy = 7,
                            Rate = 275.0,
                            Sqft = 650,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
